# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HJImagePickerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HJImagePickerDemo
  #约束布局
      pod 'Masonry'
  target 'HJImagePickerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
